spring.application.name=CourseManagment
spring.datasource.url=jdbc:mysql://localhost:3306/coursemanagment
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
